# Configure main menu and social menu
# [[social]]
# weight= 1
# identifier = "home"
# name = "Home"
# url = "/"
# [social.params]
# icon = "home"
# newtab = true

[[social]]
weight= 1
identifier = "mail"
name = "Mail"
url = "mailto:website@xavernitsch.de"

[social.params]
icon = "mail"

[[social]]
weight= 2
identifier = "github"
name = "GitHub"
url = "https://github.com/nitschSB"

[social.params]
icon = "brand-github"

[[social]]
identifier = "xing"
name = "XING"
url = "https://www.xing.com/profile/Mario_Melcher4/"

[social.params]
icon = "brand-xing"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/mario-m-physicist/"

[social.params]
icon = "brand-linkedin"
