# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/nitschSB"

[social.params]
icon = "brand-github"

[[social]]
identifier = "mail"
name = "Mail"
url = "mailto:website@xavernitsch.de"

[social.params]
icon = "mail"

[[social]]
identifier = "xing"
name = "XING"
url = "https://www.xing.com/profile/Mario_Melcher4/"

[social.params]
icon = "brand-xing"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/mario-m-physicist/"

[social.params]
icon = "brand-linkedin"
